# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gw < Formula
  desc "Git worktree wrapper - simplify git worktree management"
  homepage "https://github.com/t98o84/gw"
  version "0.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/t98o84/gw/releases/download/v0.3.10/gw_0.3.10_darwin_amd64.tar.gz"
      sha256 "35c88537c123a16be5ac3b735a3b9c870151169c2b4cf5c9a9513b0a15475492"

      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/t98o84/gw/releases/download/v0.3.10/gw_0.3.10_darwin_arm64.tar.gz"
      sha256 "a255307ff590d4df12a33dc7a4a7d5e5a0259f1476475bc319652174023efab6"

      def install
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/t98o84/gw/releases/download/v0.3.10/gw_0.3.10_linux_amd64.tar.gz"
      sha256 "de43c42a97b28d004b5ef2c642faa15288387e49599a54160466d4c4fc75df41"
      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/t98o84/gw/releases/download/v0.3.10/gw_0.3.10_linux_arm64.tar.gz"
      sha256 "88b2f421226a25163f4f34d7d183ba243a704d0a2d84aa8d3800942e2b3e78e5"
      def install
        bin.install "gw"
      end
    end
  end

  test do
    system "#{bin}/gw", "--version"
  end
end
