# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gw < Formula
  desc "Git worktree wrapper - simplify git worktree management"
  homepage "https://github.com/t98o84/gw"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/t98o84/gw/releases/download/v0.1.0/gw_0.1.0_darwin_amd64.tar.gz"
      sha256 "64df6a15166c1540974d64560d0e8bdf9e8cd1508b11e18fc3f248c866e3a46a"

      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/t98o84/gw/releases/download/v0.1.0/gw_0.1.0_darwin_arm64.tar.gz"
      sha256 "5fb376ce515bd2141237e9f53902d8b7b3f2caba48e4aca209dee77442bcf7e2"

      def install
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/t98o84/gw/releases/download/v0.1.0/gw_0.1.0_linux_amd64.tar.gz"
      sha256 "1d46f91f350c7ad6fade4cf3a064a2efa7bf3953dfcf7282bc9dfc6e6bb7a68a"
      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/t98o84/gw/releases/download/v0.1.0/gw_0.1.0_linux_arm64.tar.gz"
      sha256 "827d0d9d2015568c25bfed2de60c34da8a8049aaa04d5e2796dc44211c934618"
      def install
        bin.install "gw"
      end
    end
  end

  test do
    system "#{bin}/gw", "--version"
  end
end
